### ISSUE TITLE
majorTicks array not scaling to minValue and maxValue

### ISSUE THREAD

**Issue by jmridge** [Mikhus/canvas-gauges#84] opened 2016-11-08 01:15 UTC
I am creating a radial gauge with minValue =-10 and maxValue=150.  My majorTicks array is [-10,30,60,90,150].  minorTicks=10.  Each tick thus corresponds to 4 units.  When my gauge is displayed, the ticks are evenly displayed around the dial, and the 60 is at the top center position.  Given the underlying scale, the top value should correspond to 80 (4 units per tick), and the 60 should be displayed 5 ticks to the left of top center.  Thus, the numbers shown on the scale do not correctly match the actual value.  It seems like the majorTicks array is independent of the underlying scale range.  The highlights array is working correctly, as the end points do match the data.

Please tell me what I may be doing wrong.

Thank you for a great library.

**Comment by jmridge** [comment] 2016-11-08 12:58
Correction:  The top center value on my scale should be 70, not 80 as stated above.   Sorry.

**Comment by Mikhus** [comment] 2016-12-01 11:05
Could you please provide a code example?

**Comment by Mikhus** [comment] 2016-12-19 18:40
Fixed in 2.1.1 branch

**Comment by jmridge** [comment] 2016-12-21 09:00
Mr. Stadnyk,

Thank you for the update.  Sorry I missed your request for a code sample.

Thank you also for a great product.

Sincerely,

John M. Ridge

**Comment by Mikhus** [comment] 2016-12-24 10:10
Still investigating this. Merge reverted. Re-opening.

@jmridge To let me understand better, please, provide me with actual example where you have the problem.

**Comment by Mikhus** [comment] 2016-12-24 10:33
I see. So yes, there is misunderstanding. 
Major ticks array contains not the values but defines a number of ticks on a bar (which is array length) and as array values it provides a LABELS for those ticks. Or by another words it means bar will be split into an EQUAL BY LENGTH chunks correspondingly to array length and for each tick it will use the value from that array as LABEL. It is done like this to provide an ability to put arbitrary texts for the ticks (and we can see it, for example in a compass-like gauge implementation, where we use letters instead of numbers). I understand that your goal is probably to draw major ticks in the exact positions of values, but currently it is not supported. To do that it should be some specific gauge mode introduced and this is another feature which currently is not implemented.

**Comment by jmridge** [comment] 2016-12-24 21:44
Mr. Stadnyk,

Thank you for the detailed reply.  When I looked at your code, I determined
that the function operated as you described in your most recent e-mail
message.  I will try to come up with some way to accomplish our goal.  When
I do, I will send you the result.

Thank you again for your support.

Sincerely,

John M. Ridge

**Comment by Mikhus** [comment] 2016-12-25 12:24
Currently gauges support only linear tick bars. Means each tick (major or minor is the same distance between each other). The described bar of [-10,30,60,90,150] with 10 minor ticks between major ticks is not linear (4 units per minor ticks in the first and last major ticks sections, 3 units per minor ticks for other sections). This a bit complicated case because it have to influence not only ticks drawing but a value positioning on a bar (needle positioning angle also depends on a ticks location). For example, on a such bar density of the minor ticks between -10 and 30 will be lower in comparison to density of the ticks between 30 and 60. It means when we change a value by 1 minor tick we have to rotate different angle depending on which range value is set. Or there should be another way to split the different majorTicks ranges to a different number of minor ticks units to make such kind of a bar linear. In both cases implementation is non trivial and will cause some visual ugly drawing depending on selected numbers.
I don't understand why it is required add that kind of visualization complexity. Usually if we measuring/displaying some value in a min/max range it is OK to split that range into the same-kind linear units. If you have any strong arguments to have some non-linear bars, please, let me know them.
So I can simply propose to modify major ticks labels to a proper values just to have linear ticks bar representation here and it would be [-10, 30, 70, 110, 150] and the problem is solved.

**Comment by Mikhus** [comment] 2016-12-28 22:23
Exact value tick bars implemented in v2.1.1.

**Closed by Mikhus** 2016-12-28 22:23 UTC
Labels: enhancement

**Comment by jmridge** [comment] 2016-12-29 16:35
Mr. Stadnyk,

Sorry for my late reply.  I was traveling, and my Internet connection was
horrible.

I appreciate the time you have taken to address my question.

When I first started using the major ticks option, I did not realize that
it was a simple equal division of the entire temperature range based on the
two endpoints.  In my application, I did not want a separate scale
throughout the temperature range.  I just wanted to add extra ticks at
specific points on the scale.  For example, if my temperature range was -10
to 100 degrees, and I was interested in the sub-range of 20-40 degrees, I
might want tick marks at -10, 20, 25, 30, 35, 40, and 100 degrees.  I am
using the color highlighting, which seems to scale according to the actual
value on the scale.  So if I wanted the area between 20 and 30 degrees to
be yellow, and 30 to 40 degrees to be green, I could highlight the relevant
range.

I am also allowing users to adjust the tick marks and range, so it is
important that I understand exactly how everything works so that I can
explain details to my users.

Now that I know how everything works, I can adjust my code and
documentation accordingly.

I really enjoy working with you and your code.

Thank you for your support.

Sincerely,

John M. Ridge

**Comment by jmridge** [comment] 2016-12-29 16:36
Mr. Stadnyk,

Does this mean that the code now works like I originally thought?

John M. Ridge

**Comment by Mikhus** [comment] 2016-12-29 18:13
Hello, Mr. John!

There is 2 different modes for the tick bars available now. By default it keeps old behavior, when the entire range is split into an equal chunks and minor ticks divides each major chink into a given number of equal minor chunks.

Now it is possible to turn on drawing major ticks at exact values, specified by major ticks array, and minor ticks will define then the exact value step for each minor tick. Here is an [example](https://rawgit.com/Mikhus/canvas-gauges/master/examples/exact-ticks-bar.html) [[example source code](https://github.com/Mikhus/canvas-gauges/blob/master/examples/exact-ticks-bar.html)], showing how it works.

[Here](https://canvas-gauges.com/documentation/user-guide/configuration#ticks-bar-options) you can find docs.

I hope this mode will allow you to implement exactly what you need.
Currently this is implemented since version 2.1.1 which was released today and is already available.

All kind regards,
Mike

**Comment by jmridge** [comment] 2016-12-29 21:02
Mike,

You rock!!!

Thanks again.

Sincerely,

John
